{
 "title": "Call Analytics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "label_values(ucaas_status_code, hostname)"
   },
   {
    "name": "status",
    "query": "label_values(ucaas_status_code, status_code)"
   },
   { "name": "per", "label": "groupBy", "query": "hostname, status_code" }
  ]
 },
 "panels": [
  {
   "title": "SIP Status Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ucaas_status_code{hostname=~\"${hostname:pipe}\", status_code=~\"${status:pipe}\"}[1m])) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "SIP Status Code 4xx",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(ucaas_status_code{hostname=~\"${hostname:pipe}\", status_code=~\"4..\"}[1m]))",
     "legendFormat": "{{per}}"
    }
   ]
  },
  {
   "title": "Avg MOS Score - CDR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(ucaas_avg_mos_score{hostname=~\"${hostname:pipe}\"}) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Status Codes Over Last 24H",
   "type": "table",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "expr": "sum(delta(ucaas_status_code{hostname=~\"${hostname:pipe}\", status_code=~\".*\"}[24h])) by (status_code)"
    }
   ]
  },
  {
   "title": "Call Volume - CDR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ucaas_call_volume{hostname=~\"${hostname:pipe}\"}) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Avg Call Duration - CDR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(ucaas_avg_call_duration{hostname=~\"${hostname:pipe}\"}) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Avg PDD - CDR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(ucaas_avg_pdd{hostname=~\"${hostname:pipe}\"}) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Unique Call Legs - SIP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ucaas_unique_leg_count{hostname=~\"${hostname:pipe}\"}) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}