{
 "title": "Collection Observability",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "cluster",
    "query": "label_values(dashbase_table_info, app)"
   },
   {
    "name": "table",
    "query": "label_values(dashbase_table_info{app='$app'}, table)"
   },
   {
    "name": "hostname",
    "query": "label_values(http_filebeat_events_active, host)"
   }
  ]
 },
 "panels": [
  { "title": "Filebeat Input vs Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Local Probe - Write Rate",
   "type": "graph",
   "description": "Dashbase Night-Watch Probe\n\nhttps://github.com/dashbase/night-watch",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(nightwatch_metric_file_append_total_size{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}[5m])",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "nightwatch-metric",
     "select": [
      [
       { "params": [ "file-append-total-size" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Filebeat Final Output Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "rate(http_libbeat_output_write_bytes{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}[5m])",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "http",
     "query": "SELECT difference(\"libbeat_output_write_bytes\") FROM \"http\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "libbeat_output_write_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Received %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "proxy:filebeat:original_bytes_received:sum / on(host, table) rate(nightwatch_metric_file_append_total_size{host=~\"${hostname:pipe}\",table=~\"${table:pipe}\"}[5m])",
     "legendFormat": "received {{host}}"
    }
   ]
  },
  { "title": "Harvesters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Harvesters Running",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "http_filebeat_harvester_running{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "http",
     "select": [
      [
       { "params": [ "filebeat_harvester_running" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Harvesters Skipped/Truncated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "skipped - $tag_host",
     "expr": "http_filebeat_harvester_skipped{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "skipped - {{ host }}",
     "measurement": "http",
     "select": [
      [
       { "params": [ "filebeat_harvester_skipped" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "truncated - $tag_host",
     "expr": "http_filebeat_input_log_files_truncated{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "truncated - {{ host }}",
     "measurement": "http",
     "select": [
      [
       {
        "params": [
         "filebeat_input_log_files_truncated"
        ],
        "type": "field"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Output Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "read - $tag_host",
     "expr": "http_libbeat_output_read_errors{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "read - {{ host }}",
     "measurement": "http",
     "select": [
      [
       { "params": [ "libbeat_output_read_errors" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "write - $tag_host",
     "expr": "http_libbeat_output_write_errors{host=~\"${hostname:pipe}\", table=~\"${table:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "write - {{ host }}",
     "measurement": "http",
     "select": [
      [
       { "params": [ "libbeat_output_write_errors" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}