{
 "title": "Dashbase API",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(dashbase_table_info, app)"
   },
   { "name": "duration", "query": "1m,5m,15m" },
   {
    "name": "table",
    "query": "label_values(dashbase_table_info, table)"
   }
  ]
 },
 "panels": [
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query Count(Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(dashbase_query_count{app=\"$app\", component=\"api\", table=\"$table\"}[1h]))"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Query per Second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_query_count{app=\"$app\", component=\"api\", table=\"$table\"}[$duration])) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "User Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "User per Second" }
   ],
   "targets": [
    {
     "expr": "sum (sum by (account,table) (rate(dashbase_query_count{app=\"$app\",component=\"api\",table=\"$table\"}[$duration]))) > 0",
     "legendFormat": "users / sec"
    }
   ]
  },
  {
   "title": "Query Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(query_latency_ms_sum{app=\"$app\",component=\"api\"}[$duration]) / rate(query_latency_ms_count{app=\"$app\",component=\"api\"}[$duration]))",
     "legendFormat": "average"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "instance count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(up{app='$app',component='api'}) by (component)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "jvm_cpu_usage_percent{component='api',app='$app'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "expr": " max(jvm_attribute_uptime{component='api',app='$app'})"
    }
   ]
  },
  {
   "title": "GC time spent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_G1_Young_Generation_time{app='$app',component='api'}[$duration])",
     "legendFormat": "young gen - {{instance}}"
    },
    {
     "expr": "rate(jvm_gc_G1_Old_Generation_time{app='$app',component='api'}[$duration])",
     "legendFormat": "old gen - {{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_heap_used{component='api',app='$app'}",
     "legendFormat": "used - {{instance}}"
    },
    {
     "expr": "jvm_memory_heap_max{component='api',app='$app'}",
     "legendFormat": "max - {{instance}}"
    }
   ]
  }
 ]
}