{
 "title": "Dashbase Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "cluster",
    "query": "label_values(dashbase_table_info, app)"
   },
   {
    "name": "table",
    "query": "label_values(dashbase_table_info{app='$app'}, table)"
   },
   { "name": "duration", "query": "1m,5m,15m" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(label_replace (kube_deployment_labels{label_dashbase_io=\"true\",label_app=\"$app\"} * on (deployment,exported_namespace,instance) (kube_deployment_status_replicas_available), \"component\", \"$1\", \"deployment\", \"(.+)\") ) by (component)\nor\nsum(label_replace (kube_statefulset_labels{label_dashbase_io=\"true\",label_app=\"$app\"} * on (statefulset,exported_namespace,instance) (kube_statefulset_status_replicas_ready), \"component\", \"$1\", \"statefulset\", \"(.+)\") ) by (component)"
    },
    {
     "expr": "sum(label_replace (kube_deployment_labels{label_dashbase_io=\"true\",label_app=\"$app\"} * on (deployment,exported_namespace,instance) (kube_deployment_status_replicas_available == bool on(deployment,exported_namespace,instance) kube_deployment_spec_replicas), \"component\", \"$1\", \"deployment\", \"(.+)\") ) by (component)\nor\nsum(label_replace (kube_statefulset_labels{label_dashbase_io=\"true\",label_app=\"$app\"} * on (statefulset,exported_namespace,instance) (kube_statefulset_status_replicas_ready == bool on(statefulset,exported_namespace,instance) kube_statefulset_replicas), \"component\", \"$1\", \"statefulset\", \"(.+)\") ) by (component)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "errors observed from Dashbase services",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_proxy_events_parse_error_total{app='$app'}[$duration])) by (topic) > 0",
     "legendFormat": "proxy {{topic}} - parse error"
    },
    {
     "expr": "proxy:kafka_failure:sum{app='$app'} > 0",
     "legendFormat": "proxy - kafka failure"
    },
    {
     "expr": "proxy:overflow_message:sum{app='$app'} > 0",
     "legendFormat": "message overflow"
    },
    {
     "expr": "sum(rate(dashbase_index_event_parse_error{table=~'${table:pipe}',app='$app'}[$duration])) by (table) > 0",
     "legendFormat": "table {{table}} - input parse error"
    },
    {
     "expr": "sum(rate(io_dashbase_http_es_IndexResource_bulkPost_exceptions_total{table=~'${table:pipe}',app='$app'}[$duration])) by (table) > 0",
     "legendFormat": "table {{table}} - input rest exception"
    },
    {
     "expr": "sum(rate(dashbase_parse_error_total{table=~'${table:pipe}',app='$app'}[$duration])) by (table) > 0",
     "legendFormat": "table {{table}} - index parse error"
    },
    {
     "expr": "sum(rate(dashbase_parse_skipped_total{table=~'${table:pipe}',app='$app'}[$duration])) by (table) > 0",
     "legendFormat": "table {{table}} - skipped"
    },
    {
     "expr": "rate(dashbase_api_partition_errors_total{root=~'${table:pipe}',app='$app'}[$duration]) + rate(dashbase_api_partition_timeouts_total{root=~'${table:pipe}',app='$app'}[$duration]) > 0",
     "legendFormat": "api - error calling tables"
    },
    {
     "expr": "proxy:bulk_post_exception:sum{app='$app'} > 0",
     "legendFormat": "proxy - exception"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_cpu_usage_percent{app='$app',component!='proxy'}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "proxy:cpu:max{app='$app'}", "legendFormat": "proxy" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_heap_usage{app='$app',component!=\"proxy\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "proxy:heap_usage:max{app='$app'}",
     "legendFormat": "proxy"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "% used" }
   ],
   "targets": [
    {
     "expr": "1 - avg(dashbase_disk_available_bytes{table=~'${table:pipe}',app='$app'} / dashbase_disk_total_bytes{table=~'${table:pipe}',app='$app'}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(kafka_log_log_size{app=\"$app\"}) by (app, instance)\n        /\n      on(app, instance)\n        label_replace(\n          label_replace(\n            kube_persistentvolumeclaim_resource_requests_storage_bytes{persistentvolumeclaim=~\"kafka.*\"},\n            \"instance\", \"$1\", \"persistentvolumeclaim\", \"kafka-data-(.+)\"),\n          \"app\", \"$1\", \"exported_namespace\", \"(.+)\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_attribute_uptime{app=\"$app\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Table - $table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }, "repeat": "table" },
  {
   "title": "Ingestion Throughput",
   "type": "graph",
   "description": "How fast Dashbase is ingesting (accepting) input data. \"original\" is only counting the size of the original log messages.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_index_event_size_sum{app=\"$app\",table=~\"${table:pipe}\"}[$duration])) by (instance)",
     "legendFormat": "filebeat -> {{instance}}"
    },
    {
     "expr": "sum(rate(dashbase_filebeat_parser_message_bytes_received{app=\"$app\",table=~\"${table:pipe}\"}[$duration])) by (instance) > 0",
     "legendFormat": "filebeat -> {{instance}} (original)"
    },
    {
     "expr": "avg(dashbase_firehose_kafka_consumer_fetch_manager_metrics_bytes_consumed_rate{table=~'${table:pipe}',app='$app'}) by (instance)",
     "legendFormat": "kafka -> {{instance}}"
    },
    {
     "expr": "sum(rate(dashbase_proxy_bytes_received{app=\"$app\",topic=\"$table\"}[$duration])) by (instance)",
     "legendFormat": "{{instance}} -> kafka"
    }
   ]
  },
  {
   "title": "Ingestion / Index",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_ingestion_events_total{table=~'${table:pipe}',app='$app'}[$duration])) by (instance)",
     "legendFormat": "ingested - {{instance}}"
    },
    {
     "expr": "avg(rate(dashbase_indexer_events_total{table=~'${table:pipe}',app='$app'}[$duration])) by (instance)",
     "legendFormat": "indexed - {{instance}}"
    }
   ]
  },
  {
   "title": "Ingestion Delay",
   "type": "graph",
   "description": "Delay from event produce until searchable",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_indexer_full_latency_secs_sum{table=~'${table:pipe}',app='$app'}[$duration]) / rate(dashbase_indexer_full_latency_secs_count{table=~'${table:pipe}',app='$app'}[$duration])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time Range",
   "type": "graph",
   "description": "How long ago the oldest segment in Table was built.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "expr": "dashbase_actual_retention_days{app=\"$app\",table=~\"${table}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Query/User Per Second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_search_query_latency_secs_count{table=~'${table:pipe}',app='$app'}[$duration])) by (table) > 0",
     "legendFormat": "queries / sec"
    },
    {
     "expr": "sum (sum by (account,table) (rate(dashbase_query_count{app=\"$app\",component=\"api\",table=~\"$table(/.+)?|\\\\*\"}[$duration]))) > 0",
     "legendFormat": "users / sec"
    }
   ]
  },
  {
   "title": "Query Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_search_query_latency_secs_sum{table=~'${table:pipe}',app='$app'}[$duration]) / rate(dashbase_search_query_latency_secs_count{table=~'${table:pipe}',app='$app'}[$duration])) by (table) > 0",
     "legendFormat": "{{table}}"
    }
   ]
  }
 ]
}