{
 "title": "Dashbase Table",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(dashbase_table_info, app)"
   },
   {
    "name": "table",
    "query": "label_values(dashbase_table_info{app='$app'}, table)"
   },
   { "name": "duration", "query": "1m,5m,15m" },
   { "name": "per", "label": "groupBy", "query": "table,instance" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingestion Throughput",
   "type": "graph",
   "description": "How fast Dashbase is ingesting (accepting) input data. \"original\" is only counting the size of the original log messages.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_index_event_size_sum{component='table', app=\"$app\",table=~\"${table:pipe}\"}[$duration])) by ($per)",
     "legendFormat": "filebeat -> {{$per}}"
    },
    {
     "expr": "sum(rate(dashbase_filebeat_parser_message_bytes_received{component='table', app=\"$app\",table=~\"${table:pipe}\"}[$duration])) by ($per) > 0",
     "legendFormat": "filebeat -> {{$per}} (original)"
    },
    {
     "expr": "sum(dashbase_firehose_kafka_consumer_fetch_manager_metrics_bytes_consumed_rate{component='table', table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "kafka -> {{$per}}"
    },
    {
     "expr": "sum(rate(dashbase_proxy_bytes_received{component='table', app=\"$app\",topic=\"$table\"}[$duration])) by ($per)",
     "legendFormat": "{{$per}} -> kafka"
    }
   ]
  },
  {
   "title": "Ingestion / Index",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_ingestion_events_total{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "ingested - {{$per}}"
    },
    {
     "expr": "sum(rate(dashbase_indexer_events_total{component='table', table=~'${table:pipe}',app='$app',type='full'}[$duration])) by ($per)",
     "legendFormat": "indexed - {{$per}}"
    }
   ]
  },
  {
   "title": "Ingestion Delay (Max)",
   "type": "graph",
   "description": "Delay from event produce until searchable",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(dashbase_indexer_full_latency_secs_sum{component='table', table=~'${table:pipe}',app='$app',type='full'}[$duration]) / rate(dashbase_indexer_full_latency_secs_count{component='table', table=~'${table:pipe}',app='$app',type='full'}[$duration])) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "Retention in Days",
   "type": "graph",
   "description": "How long ago the oldest segment in Table was built.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Days" }
   ],
   "targets": [
    {
     "expr": "avg(dashbase_actual_retention_days{app=\"$app\",component='table', table=~\"${table}\"}) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Query Per Second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_search_query_latency_secs_count{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "Query Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_search_query_latency_secs_sum{component='table', table=~'${table:pipe}',app='$app'}[5m]) / rate(dashbase_search_query_latency_secs_count{component='table', table=~'${table:pipe}',app='$app'}[5m])) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "HTTP _bulk endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dashbase_index_event_size_sum{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "bytes - {{$per}}"
      },
      {
       "expr": "sum(rate(dashbase_index_event_size_count{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "events - {{$per}}"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(io_dashbase_elasticsearch_resource_IndexResource_bulkPost_count{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(io_dashbase_elasticsearch_resource_IndexResource_bulkPost{quantile='0.5',component='table', app='$app',table=~'${table:pipe}'}) by ($per)",
       "legendFormat": "p50 - {{$per}}"
      },
      {
       "expr": "avg(io_dashbase_elasticsearch_resource_IndexResource_bulkPost{quantile='0.99',component='table', app='$app',table=~'${table:pipe}'}) by ($per)",
       "legendFormat": "p99 - {{$per}}"
      }
     ]
    },
    {
     "title": "Error",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dashbase_index_event_parse_error{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "parse error - {{$per}}"
      },
      {
       "expr": "sum(rate(dashbase_overflow_message{component='table', table=~'${table:pipe}',app='$app',component='table'}[$duration])) by ($per)",
       "legendFormat": "overflow - {{$per}}"
      },
      {
       "expr": "sum(rate(io_dashbase_elasticsearch_resource_IndexResource_bulkPost_exceptions_total{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "exception - {{$per}}"
      }
     ]
    },
    {
     "title": "Delay",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(dashbase_index_event_delay_sum{component='table', table=~'${table:pipe}',app='$app'}[$duration])/rate(dashbase_index_event_delay_count{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "average - {{$per}}"
      },
      {
       "expr": "1 - avg(rate(dashbase_index_event_delay_bucket{component='table', table=~'${table:pipe}',app='$app',le=\"60.0\"}[$duration])/ignoring(le) rate(dashbase_index_event_delay_count{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "% > 1m - {{$per}}"
      },
      {
       "expr": "1 - avg(rate(dashbase_index_event_delay_bucket{component='table', table=~'${table:pipe}',app='$app',le=\"3600.0\"}[$duration])/ignoring(le) rate(dashbase_index_event_delay_count{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "% > 1h - {{$per}}"
      }
     ]
    },
    {
     "title": "Event Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "floor(avg(rate(dashbase_index_event_size_sum{component='table', table=~'${table:pipe}',app='$app'}[$duration])/rate(dashbase_index_event_size_count{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per))",
       "legendFormat": "avg - {{$per}}"
      },
      {
       "expr": "1 - avg(rate(dashbase_index_event_size_bucket{component='table', table=~'${table:pipe}',app='$app',le=\"1048576.0\"}[$duration])/ignoring(le) rate(dashbase_index_event_size_count{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "% > 1MB - {{$per}}"
      },
      {
       "expr": "1 - avg(rate(dashbase_index_event_size_bucket{component='table', table=~'${table:pipe}',app='$app',le=\"1.048576E7\"}[$duration])/ignoring(le) rate(dashbase_index_event_size_count{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "% > 10MB - {{$per}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Firehose",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Record Lag Max",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      {
       "format": "short",
       "label": "Number of Records Behind Producer"
      }
     ],
     "targets": [
      {
       "expr": "sum(clamp_min(dashbase_firehose_kafka_consumer_fetch_manager_metrics_records_lag_max{table=~'${table:pipe}',app='$app'},0)) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Consumption Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dashbase_firehose_kafka_consumer_fetch_manager_metrics_records_consumed_rate{table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "records - {{$per}}"
      },
      {
       "expr": "sum(dashbase_firehose_kafka_consumer_fetch_manager_metrics_bytes_consumed_rate{table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "bytes - {{$per}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Chronicle Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read / Write",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dashbase_index_chronicle_queue_read_sum{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "read - {{$per}}"
      },
      {
       "expr": "sum(rate(dashbase_index_chronicle_queue_write_sum{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "write - {{$per}}"
      }
     ]
    },
    {
     "title": "# entries in the queue",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dashbase_index_chronicle_queue_num_entries{component='table', table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "# files",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dashbase_index_chronicle_queue_num_files{component='table', table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "health check",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(dashbase_index_chronicle_queue_health{component='table', table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indexing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "# events indexed / sec" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dashbase_ingestion_events_total{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "events - {{$per}}"
      },
      {
       "expr": "sum(rate(dashbase_ingestion_bytes_total{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": " bytes - {{$per}}"
      }
     ]
    },
    {
     "title": "Parse Error",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dashbase_parse_error_total{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "parse error - {{$per}}"
      },
      {
       "expr": "sum(rate(dashbase_parse_skipped_total{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "skipped - {{$per}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "Query Per Second" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dashbase_search_query_latency_secs_count{component='table', table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(dashbase_search_query_latency_secs_sum{component='table', table=~'${table:pipe}',app='$app'}[5m]) / rate(dashbase_search_query_latency_secs_count{component='table', table=~'${table:pipe}',app='$app'}[5m])) by ($per)",
       "legendFormat": "average - {{$per}}"
      },
      {
       "expr": "avg(histogram_quantile(0.99, rate(dashbase_search_query_latency_secs_bucket{component='table', table=~'${table:pipe}',app='$app'}[5m]))) by ($per)",
       "legendFormat": "p99 - {{$per}}"
      }
     ]
    },
    {
     "title": "Query failures",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dashbase_api_partition_errors_total{root=~'${table:pipe}',app='$app'}[5m])",
       "legendFormat": "errors - {{root}} - {{partition}}"
      },
      {
       "expr": "rate(dashbase_api_partition_timeouts_total{root=~'${table:pipe}',app='$app'}[5m])",
       "legendFormat": "timeouts - {{root}} - {{partition}}"
      }
     ]
    },
    {
     "title": "Wait-in-queue latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(dashbase_search_wait_latency_secs_sum{table=~'${table:pipe}',app='$app'}[5m])/rate(dashbase_search_wait_latency_secs_count{table=~'${table:pipe}',app='$app'}[5m])) by ($per)",
       "legendFormat": "average - {{$per}}"
      },
      {
       "expr": "avg(histogram_quantile(0.99,rate(dashbase_search_wait_latency_secs_bucket{table=~'${table:pipe}',app='$app'}[5m]))) by ($per)",
       "legendFormat": "p99 - {{$per}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Counts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dashbase_index_timeslice_count{table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Reader Cache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dashbase_search_reader_cache_count{table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Range",
     "type": "graph",
     "description": "{newest timestamp in a segment} - {oldest timestamp in a segment}",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(dashbase_indexer_time_slice_range_secs_sum{component='table', table=~'${table:pipe}',app='$app',type='full'}[$duration]) / rate(dashbase_indexer_time_slice_range_secs_count{component='table', table=~'${table:pipe}',app='$app',type='full'}[$duration])) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Range (Realtime)",
     "type": "graph",
     "description": "{newest timestamp in a segment} - {oldest timestamp in a segment}",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(dashbase_indexer_time_slice_range_secs_sum{component='table', table=~'${table:pipe}',app='$app',type='realtime'}[$duration]) / rate(dashbase_indexer_time_slice_range_secs_count{component='table', table=~'${table:pipe}',app='$app',type='realtime'}[$duration])) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Delay",
     "type": "graph",
     "description": "{Time when a segment was built} - {timestamp of each event}",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(dashbase_indexer_full_latency_secs_sum{component='table', table=~'${table:pipe}',app='$app',type='full'}[$duration]) / rate(dashbase_indexer_full_latency_secs_count{component='table', table=~'${table:pipe}',app='$app',type='full'}[$duration])) by ($per)",
       "legendFormat": "average - {{$per}}"
      }
     ]
    },
    {
     "title": "Delay (Realtime)",
     "type": "graph",
     "description": "{Time when a segment was built} - {timestamp of each event}",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(dashbase_indexer_full_latency_secs_sum{component='table', table=~'${table:pipe}',app='$app',type='realtime'}[$duration]) / rate(dashbase_indexer_full_latency_secs_count{component='table', table=~'${table:pipe}',app='$app',type='realtime'}[$duration])) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Avg Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg((dashbase_total_index_bytes{component='table', table=~'${table:pipe}',app='$app'} + dashbase_total_payload_bytes{component='table', table=~'${table:pipe}',app='$app'})/dashbase_index_timeslice_count{component='table', table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Avg Raw Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(dashbase_total_raw_bytes{component='table', table=~'${table:pipe}',app='$app'}/dashbase_index_timeslice_count{component='table', table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Flush Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(rate(dashbase_indexer_flush_bytes_sum{component='table', table=~'${table:pipe}',app='$app',type='full'}[$duration])/rate(dashbase_indexer_flush_bytes_count{component='table', table=~'${table:pipe}',app='$app',type='full'}[$duration])) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Flush Size (Realtime)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(rate(dashbase_indexer_flush_bytes_sum{component='table', table=~'${table:pipe}',app='$app',type='realtime'}[$duration])/rate(dashbase_indexer_flush_bytes_count{component='table', table=~'${table:pipe}',app='$app',type='realtime'}[$duration])) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bloomfilter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Files Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dashbase_bloomfilter_files_count{table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Elements Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dashbase_bloomfilter_elements_count{table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(dashbase_bloomfilter_ram_used_MB{table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Disk",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(dashbase_bloomfilter_disk_used_MB{table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Positive Query Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dashbase_bloomfilter_positive_query_count{table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Negative Query Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dashbase_bloomfilter_negative_query_count{table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    },
    {
     "title": "Unknown Segment Query Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dashbase_bloomfilter_unknown_segment_query_count{table=~'${table:pipe}',app='$app'}) by ($per)",
       "legendFormat": "{{$per}}"
      }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "min(jvm_attribute_uptime{component='table',table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_cpu_usage_percent{component='table',table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_heap_used{component='table',table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "{{$per}}"
    },
    {
     "expr": "sum(jvm_memory_heap_max{component='table',table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "max - {{$per}}"
    }
   ]
  },
  {
   "title": "GC time spent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(jvm_gc_G1_Young_Generation_time{app='$app',component='table',table=~'${table:pipe}'}[$duration])) by ($per)",
     "legendFormat": "young gen - {{$per}}"
    },
    {
     "expr": "sum(irate(jvm_gc_G1_Old_Generation_time{app='$app',component='table',table=~'${table:pipe}'}[$duration])) by ($per)",
     "legendFormat": "old gen - {{$per}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(dashbase_disk_used_bytes{component='table', table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "reported used bytes - {{$per}}"
    },
    {
     "expr": "sum(dashbase_disk_total_bytes{component='table', table=~'${table:pipe}',app='$app'} - dashbase_disk_available_bytes{component='table', table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "actual used bytes - {{$per}}"
    },
    {
     "expr": "sum(dashbase_disk_total_bytes{component='table', table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "total bytes - {{$per}}"
    }
   ]
  },
  {
   "title": "Index Disk Breakdown",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(dashbase_total_index_bytes{table=~'${table:pipe}',app='$app'} / on(instance,table) dashbase_disk_used_bytes{table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "% used by index - {{$per}}"
    },
    {
     "expr": "avg(dashbase_total_payload_bytes{table=~'${table:pipe}',app='$app'} / on(instance,table) dashbase_disk_used_bytes{table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "% used by payload - {{$per}}"
    },
    {
     "expr": "avg(dashbase_bloomfilter_disk_used_MB{table=~'${table:pipe}',app='$app'} * 1024 * 1024 / on(instance,table) dashbase_disk_used_bytes{table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "% used by bloomfilter - {{$per}}"
    },
    {
     "expr": "avg(dashbase_total_sample_size_KB{table=~'${table:pipe}',app='$app'} * 1024 / on(instance,table) dashbase_disk_used_bytes{table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "% used by sample index - {{$per}}"
    },
    {
     "expr": "avg(dashbase_disk_available_bytes{component='table', table=~'${table:pipe}',app='$app'} / on(instance,table) dashbase_disk_total_bytes{component='table', table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "% disk free - {{$per}}"
    },
    {
     "expr": "avg((dashbase_total_payload_bytes{table=~'${table:pipe}',app='$app'} + dashbase_total_index_bytes{table=~'${table:pipe}',app='$app'}) / on(instance,table) dashbase_total_raw_bytes{table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "% compression ratio - {{$per}}"
    }
   ]
  }
 ]
}