{
 "title": "Dashbase Table Manager",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(jvm_attribute_uptime, app)"
   },
   {
    "name": "table",
    "query": "label_values(jvm_attribute_uptime{app='$app'}, table)"
   },
   { "name": "duration", "query": "1m,5m,15m" },
   { "name": "per", "label": "groupBy", "query": "table,instance" }
  ]
 },
 "panels": [
  { "title": "Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_table_manager_query_latency_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "Query Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_table_manager_query_latency_sum{table=~'${table:pipe}',app='$app'}[$duration]) / rate(dashbase_table_manager_query_latency_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "{{$per}} - avg"
    },
    {
     "expr": "quantile(0.90, rate(dashbase_table_manager_query_latency_sum{table=~'${table:pipe}',app='$app'}[$duration]) / rate(dashbase_table_manager_query_latency_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "{{$per}} - p90"
    },
    {
     "expr": "quantile(0.99, rate(dashbase_table_manager_query_latency_sum{table=~'${table:pipe}',app='$app'}[$duration]) / rate(dashbase_table_manager_query_latency_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "{{$per}} - p99"
    }
   ]
  },
  {
   "title": "Segments Searched",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(dashbase_table_manager_num_segments_searched{table=~'${table:pipe}',app='$app'}[1m])) by ($per)",
     "legendFormat": "total - {{$per}}"
    },
    {
     "expr": "avg(delta(dashbase_table_manager_num_segments_bloom_filter_checked{table=~'${table:pipe}',app='$app'}[1m]) / delta(dashbase_table_manager_num_segments_searched{table=~'${table:pipe}',app='$app'}[1m])) by ($per)",
     "legendFormat": "% bloom filter checked - {{$per}}"
    },
    {
     "expr": "avg(delta(dashbase_table_manager_num_segments_bloom_filtered{table=~'${table:pipe}',app='$app'}[1m]) / delta(dashbase_table_manager_num_segments_searched{table=~'${table:pipe}',app='$app'}[1m])) by ($per)",
     "legendFormat": "% filtered by bloom filter - {{$per}}"
    },
    {
     "expr": "avg(delta(dashbase_table_manager_num_segments_filtered_by_continuation_token{table=~'${table:pipe}',app='$app'}[1m]) / delta(dashbase_table_manager_num_segments_searched{table=~'${table:pipe}',app='$app'}[1m])) by ($per)",
     "legendFormat": "% filtered by continuation token - {{$per}}"
    }
   ]
  },
  {
   "title": "# Segments Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(dashbase_table_manager_num_segment_info{app=\"$app\",table=~'${table:pipe}'}) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "# Bloom Filters Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(dashbase_table_manager_num_segments_bloom_filter_loaded{app=\"$app\",table=~'${table:pipe}'}) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  { "title": "Autocomplete", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_table_manager_autocomplete_latency_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_table_manager_autocomplete_latency_sum{table=~'${table:pipe}',app='$app'}[$duration]) / rate(dashbase_table_manager_autocomplete_latency_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "min(jvm_attribute_uptime{component='table-manager',table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_cpu_usage_percent{component='table-manager',table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_heap_used{component='table-manager',table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "{{$per}}"
    },
    {
     "expr": "sum(jvm_memory_heap_max{component='table-manager',table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "max - {{$per}}"
    }
   ]
  },
  {
   "title": "GC time spent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(jvm_gc_G1_Young_Generation_time{app='$app',component='table-manager',table=~'${table:pipe}'}[$duration])) by ($per)",
     "legendFormat": "young gen - {{$per}}"
    },
    {
     "expr": "sum(irate(jvm_gc_G1_Old_Generation_time{app='$app',component='table-manager',table=~'${table:pipe}'}[$duration])) by ($per)",
     "legendFormat": "old gen - {{$per}}"
    }
   ]
  }
 ]
}