{
 "title": "Dashbase Searcher",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(jvm_attribute_uptime, app)"
   },
   {
    "name": "table",
    "query": "label_values(jvm_attribute_uptime{app='$app'}, table)"
   },
   { "name": "duration", "query": "1m,5m,15m" },
   { "name": "per", "label": "groupBy", "query": "table,instance" }
  ]
 },
 "panels": [
  { "title": "Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_searcher_query_latency_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "Query Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_searcher_query_latency_sum{table=~'${table:pipe}',app='$app'}[$duration]) / rate(dashbase_searcher_query_latency_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "Segments Searched",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(dashbase_searcher_num_segments_searched{table=~'${table:pipe}',app='$app'}[1m])) by ($per)",
     "legendFormat": "searched - {{$per}}"
    },
    {
     "expr": "avg(delta(dashbase_searcher_num_segments_bloom_filter_checked{table=~'${table:pipe}',app='$app'}[1m]) / delta(dashbase_searcher_num_segments_searched{table=~'${table:pipe}',app='$app'}[1m])) by ($per)",
     "legendFormat": "% bloom filter checked - {{$per}}"
    },
    {
     "expr": "avg(delta(dashbase_searcher_num_segments_bloom_filtered{table=~'${table:pipe}',app='$app'}[1m]) / delta(dashbase_searcher_num_segments_searched{table=~'${table:pipe}',app='$app'}[1m])) by ($per)",
     "legendFormat": "% filtered by bloom filter - {{$per}}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(dashbase_searcher_reader_cache_count{app=\"$app\"})",
     "legendFormat": "segment reader"
    },
    {
     "expr": "sum(dashbase_searcher_num_bloom_filters_loaded{app=\"$app\"})",
     "legendFormat": "bloom filter"
    },
    {
     "expr": "sum(caffeine_cache_estimated_size{component=\"searcher\",cache=\"payload\"})",
     "legendFormat": "payload"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jvm_attribute_uptime{component='searcher',app='$app'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "jvm_cpu_usage_percent{component='searcher',app='$app'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_heap_used{component='searcher',app='$app'}",
     "legendFormat": "heap used - {{instance}}"
    },
    {
     "expr": "jvm_memory_heap_max{component='searcher',app='$app'}",
     "legendFormat": "max - {{instance}}"
    }
   ]
  },
  {
   "title": "GC time spent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_G1_Young_Generation_time{app='$app',component='searcher'}[$duration])",
     "legendFormat": "young gen - {{instance}}"
    },
    {
     "expr": "irate(jvm_gc_G1_Old_Generation_time{app='$app',component='searcher'}[$duration])",
     "legendFormat": "old gen - {{instance}}"
    }
   ]
  }
 ]
}