{
 "title": "Dashbase Presto",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(dashbase_table_info, app)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(com_facebook_presto_metadata_discoverynodemanager_activenodecount{app='$app'})"
    }
   ]
  },
  {
   "title": "Running Queries",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(com_facebook_presto_execution_querymanager_runningqueries{app='$app',component='presto-coordinator'})"
    }
   ]
  },
  {
   "title": "Queued Queries",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(com_facebook_presto_execution_querymanager_queuedqueries{app='$app',component='presto-coordinator'})"
    }
   ]
  },
  {
   "title": "Total Failed Queries(15m)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "floor(sum(com_facebook_presto_execution_querymanager_failedqueries_fifteenminute_count{app='$app',component='presto-coordinator'}))"
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_facebook_presto_execution_querymanager_runningqueries{app='$app',component='presto-coordinator'}",
     "legendFormat": "running queries - {{instance}}"
    },
    {
     "expr": "com_facebook_presto_execution_querymanager_queuedqueries{app='$app',component='presto-coordinator'}",
     "legendFormat": "queued queries - {{instance}}"
    },
    {
     "expr": "com_facebook_presto_execution_querymanager_failedqueries_totalcount{app='$app',component='presto-coordinator'}",
     "legendFormat": "failed queries - {{instance}}"
    },
    {
     "expr": "com_facebook_presto_execution_querymanager_completedqueries_totalcount{app='$app',component='presto-coordinator'}",
     "legendFormat": "total completed queries - {{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "com_facebook_presto_execution_querymanager_executiontime_fifteenminutes_p50{app='$app',component='presto-coordinator'}",
     "legendFormat": "p50 - {{instance}}"
    },
    {
     "expr": "com_facebook_presto_execution_querymanager_executiontime_fifteenminutes_p90{app='$app',component='presto-coordinator'}",
     "legendFormat": "p90 - {{instance}}"
    },
    {
     "expr": "com_facebook_presto_execution_querymanager_executiontime_fifteenminutes_p95{app='$app',component='presto-coordinator'}",
     "legendFormat": "p95 - {{instance}}"
    },
    {
     "expr": "com_facebook_presto_execution_querymanager_executiontime_fifteenminutes_p99{app='$app',component='presto-coordinator'}",
     "legendFormat": "p99 - {{instance}}"
    }
   ]
  },
  {
   "title": "Input Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "floor(com_facebook_presto_execution_taskmanager_inputdatasize_fifteenminute_count{app='$app',component='presto-coordinator'})",
     "legendFormat": "Bytes - {{instance}}"
    },
    {
     "expr": "floor(com_facebook_presto_execution_taskmanager_inputpositions_fifteenminute_count{app='$app',component='presto-coordinator'})",
     "legendFormat": "Rows - {{instance}}"
    }
   ]
  },
  { "title": "Thrift", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "thrift_client_presto_time_fifteenminutes_p50{app='$app',component='presto-coordinator'}",
     "legendFormat": "p50 - {{instance}} - {{ method }}"
    },
    {
     "expr": "thrift_client_presto_time_fifteenminutes_p90{app='$app',component='presto-coordinator'}",
     "legendFormat": "p90 - {{instance}} - {{ method }}"
    },
    {
     "expr": "thrift_client_presto_time_fifteenminutes_p95{app='$app',component='presto-coordinator'}",
     "legendFormat": "p95 - {{instance}} - {{ method }}"
    },
    {
     "expr": "thrift_client_presto_time_fifteenminutes_p99{app='$app',component='presto-coordinator'}",
     "legendFormat": "p99 - {{instance}} - {{ method }}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{app='$app',component=\"presto-coordinator\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{app='$app',area='heap',component=\"presto-coordinator\"}",
     "legendFormat": "used - {{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{app='$app',area='heap',component=\"presto-coordinator\"}",
     "legendFormat": "max - {{instance}}"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "thread count" }
   ],
   "targets": [
    {
     "expr": "java_lang_threading_threadcount{app='$app',component='presto-coordinator'}",
     "legendFormat": "thread count - {{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{app='$app',component=\"presto-coordinator\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}