{
 "title": "Dashbase Proxy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(dashbase_table_info, app)"
   },
   {
    "name": "kafka_topic",
    "query": "label_values(dashbase_proxy_events_received{app='$app'},topic)"
   },
   { "name": "duration", "query": "1m,5m,15m" }
  ]
 },
 "panels": [
  { "title": "Input / Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proxy:events_received:sum{topic=~'${kafka_topic:pipe}',app='$app'}",
     "legendFormat": "events - {{topic}}"
    },
    {
     "expr": "proxy:bytes_received:sum{topic=~'${kafka_topic:pipe}',app='$app'}",
     "legendFormat": "bytes - {{topic}}"
    }
   ]
  },
  {
   "title": "Output",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proxy:events_sent:sum{topic=~'${kafka_topic:pipe}',app='$app'}",
     "legendFormat": "events -  {{topic}}"
    },
    {
     "expr": "proxy:bytes_sent:sum{topic=~'${kafka_topic:pipe}',app='$app'}",
     "legendFormat": "bytes - {{topic}}"
    }
   ]
  },
  {
   "title": "Total I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(proxy:events_sent:sum{topic=~'${kafka_topic:pipe}',app='$app'})",
     "legendFormat": "events out"
    },
    {
     "expr": "sum(proxy:bytes_sent:sum{topic=~'${kafka_topic:pipe}',app='$app'})",
     "legendFormat": "bytes out"
    },
    {
     "expr": "sum(proxy:events_received:sum{topic=~'${kafka_topic:pipe}',app='$app'})",
     "legendFormat": "events in"
    },
    {
     "expr": "sum(proxy:bytes_received:sum{topic=~'${kafka_topic:pipe}',app='$app'})",
     "legendFormat": "bytes in"
    }
   ]
  },
  {
   "title": "Input - _bulk POST endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "proxy:bulk_post_count:sum{app='$app'}",
     "legendFormat": "request rate"
    },
    {
     "expr": "proxy:bulk_post_exception:sum{app='$app'}",
     "legendFormat": "exception rate"
    },
    {
     "expr": "proxy:bulk_post_latency:avg{quantile='0.5',app='$app'}",
     "legendFormat": "latency (p50)"
    },
    {
     "expr": "proxy:bulk_post_latency:avg{quantile='0.95',app='$app'}",
     "legendFormat": "latency (p95)"
    },
    {
     "expr": "proxy:bulk_post_latency:avg{quantile='0.99',app='$app'}",
     "legendFormat": "latency (p99)"
    }
   ]
  },
  {
   "title": "Delays",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "proxy:event_delay:avg{topic=~'${kafka_topic:pipe}',app='$app'}",
     "legendFormat": "average - {{topic}}"
    },
    {
     "expr": "proxy:event_delay:ratio{topic=~'${kafka_topic:pipe}',app='$app'}",
     "legendFormat": "% > {{greater_than}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Event Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "proxy:event_size:avg{topic=~'${kafka_topic:pipe}',app='$app'}",
     "legendFormat": "average - {{topic}}"
    },
    {
     "expr": "proxy:event_size:ratio{topic=~'${kafka_topic:pipe}',app='$app'}",
     "legendFormat": "% > {{greater_than}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_proxy_events_parse_error{app='$app'}[$duration])) by (topic)",
     "legendFormat": "parse error - {{topic}}"
    },
    {
     "expr": "sum(rate(dashbase_proxy_events_parse_error_total{app='$app'}[$duration]))",
     "legendFormat": "parse error - total"
    },
    {
     "expr": "sum(proxy:kafka_failure:sum{app='$app'}) by (exception)",
     "legendFormat": "kafka error - {{exception}}"
    },
    {
     "expr": "proxy:overflow_message:sum{app='$app'}",
     "legendFormat": "overflow message"
    }
   ]
  },
  {
   "title": "Internal Queue Size",
   "type": "graph",
   "description": "# of events in the internal queue (which is only used to buffer events when Kafka is down)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proxy:internal_queue_size:max{topic=~'${kafka_topic:pipe}',app='$app'}",
     "legendFormat": "queue size"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Instance Count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 47 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "proxy:instance_count{app='$app'}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "proxy:cpu:max{app='$app'}", "legendFormat": "max" },
    { "expr": "proxy:cpu:avg{app='$app'}", "legendFormat": "avg" }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 56 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    { "expr": "proxy:uptime:max{app='$app'}" }
   ]
  },
  {
   "title": "GC time spent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "proxy:gc_young:max{app='$app'}", "legendFormat": "young gen - {{instance}}" },
    { "expr": "proxy:gc_old:max{app='$app'}", "legendFormat": "old gen - {{instance}}" },
    {
     "expr": "proxy:mark_sweep:max{app='$app'}",
     "legendFormat": "mark sweep - {{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "proxy:heap_used:max{app='$app'}",
     "legendFormat": "used"
    },
    { "expr": "proxy:heap_max:max{app='$app'}", "legendFormat": "max" }
   ]
  }
 ]
}