{
 "title": "Dashbase Indexer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(jvm_attribute_uptime, app)"
   },
   {
    "name": "table",
    "query": "label_values(jvm_attribute_uptime{app='$app'}, table)"
   },
   { "name": "duration", "query": "1m,5m,15m" },
   { "name": "per", "label": "groupBy", "query": "table,instance" }
  ]
 },
 "panels": [
  { "title": "Input (HTTP REST endpoint)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_index_event_size_sum{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "bytes - {{$per}}"
    },
    {
     "expr": "sum(rate(dashbase_filebeat_parser_message_bytes_received{app=\"$app\",table=~\"${table:pipe}\"}[$duration])) by ($per) > 0",
     "legendFormat": "bytes (original) - {{$per}}"
    },
    {
     "expr": "sum(rate(dashbase_index_event_size_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "events - {{$per}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(io_dashbase_elasticsearch_resource_IndexResource_bulkPost_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(io_dashbase_elasticsearch_resource_IndexResource_bulkPost{quantile='0.5',app='$app',table=~'${table:pipe}'}) by ($per)",
     "legendFormat": "p50 - {{$per}}"
    },
    {
     "expr": "avg(io_dashbase_elasticsearch_resource_IndexResource_bulkPost{quantile='0.99',app='$app',table=~'${table:pipe}'}) by ($per)",
     "legendFormat": "p99 - {{$per}}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_index_event_parse_error{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "parse error - {{$per}}"
    },
    {
     "expr": "sum(rate(dashbase_overflow_message{table=~'${table:pipe}',app='$app',component='table'}[$duration])) by ($per)",
     "legendFormat": "overflow - {{$per}}"
    },
    {
     "expr": "sum(rate(io_dashbase_elasticsearch_resource_IndexResource_bulkPost_exceptions_total{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "exception - {{$per}}"
    }
   ]
  },
  {
   "title": "Delay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_index_event_delay_sum{table=~'${table:pipe}',app='$app'}[$duration])/rate(dashbase_index_event_delay_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "average - {{$per}}"
    },
    {
     "expr": "1 - avg(rate(dashbase_index_event_delay_bucket{table=~'${table:pipe}',app='$app',le=\"60.0\"}[$duration])/ignoring(le) rate(dashbase_index_event_delay_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "% > 1m - {{$per}}"
    },
    {
     "expr": "1 - avg(rate(dashbase_index_event_delay_bucket{table=~'${table:pipe}',app='$app',le=\"3600.0\"}[$duration])/ignoring(le) rate(dashbase_index_event_delay_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "% > 1h - {{$per}}"
    }
   ]
  },
  {
   "title": "Event Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "floor(avg(rate(dashbase_index_event_size_sum{table=~'${table:pipe}',app='$app'}[$duration])/rate(dashbase_index_event_size_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per))",
     "legendFormat": "avg - {{$per}}"
    },
    {
     "expr": "1 - avg(rate(dashbase_index_event_size_bucket{table=~'${table:pipe}',app='$app',le=\"1048576.0\"}[$duration])/ignoring(le) rate(dashbase_index_event_size_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "% > 1MB - {{$per}}"
    },
    {
     "expr": "1 - avg(rate(dashbase_index_event_size_bucket{table=~'${table:pipe}',app='$app',le=\"1.048576E7\"}[$duration])/ignoring(le) rate(dashbase_index_event_size_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "% > 10MB - {{$per}}"
    }
   ]
  },
  { "title": "Chronicle Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Read / Write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_index_chronicle_queue_read_sum{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "read - {{$per}}"
    },
    {
     "expr": "sum(rate(dashbase_index_chronicle_queue_write_sum{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "write - {{$per}}"
    }
   ]
  },
  {
   "title": "# entries in the queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dashbase_index_chronicle_queue_num_entries{table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "# files",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dashbase_index_chronicle_queue_num_files{table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "health check",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(dashbase_index_chronicle_queue_health{table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  { "title": "Indexing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_ingestion_events_total{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "ingested - {{$per}}"
    },
    {
     "expr": "sum(rate(dashbase_indexer_events_total{table=~'${table:pipe}',app='$app',type='full'}[$duration])) by ($per)",
     "legendFormat": "indexed - {{$per}}"
    }
   ]
  },
  {
   "title": "Parse Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_parse_error_total{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "parse error - {{$per}}"
    },
    {
     "expr": "sum(rate(dashbase_parse_skipped_total{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "skipped - {{$per}}"
    }
   ]
  },
  {
   "title": "Segment Build Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_indexer_flush_duration_sum{table=~'${table:pipe}',app='$app'}[$duration]) / rate(dashbase_indexer_flush_duration_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per,type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "# Concurrent Builds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dashbase_indexer_concurrent_flush{table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "concurrent builds - {{$per}}"
    },
    {
     "expr": "avg(rate(dashbase_indexer_writer_waiting_time_sum{table=~'${table:pipe}',app='$app'}[$duration]) / rate(dashbase_indexer_writer_waiting_time_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per)",
     "legendFormat": "wait time - {{$per}}"
    }
   ]
  },
  {
   "title": "# Segments Built",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(increase(dashbase_indexer_flush_bytes_count{table=~'${table:pipe}',app='$app'}[1m]))) by ($per, type)",
     "legendFormat": "{{type}} segment - {{$per}}"
    }
   ]
  },
  {
   "title": "# RealTime Segments Loaded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dashbase_realtime_searcher_num_segments{table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "realtime segments - {{$per}}"
    }
   ]
  },
  {
   "title": "Range",
   "type": "graph",
   "description": "{newest timestamp in a segment} - {oldest timestamp in a segment}",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_indexer_time_slice_range_secs_sum{table=~'${table:pipe}',app='$app'}[$duration]) / rate(dashbase_indexer_time_slice_range_secs_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per, type)",
     "legendFormat": "{{type}} segments - {{$per}}"
    }
   ]
  },
  {
   "title": "Delay",
   "type": "graph",
   "description": "{Time when a segment was built} - {timestamp of each event}",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_indexer_full_latency_secs_sum{table=~'${table:pipe}',app='$app'}[$duration]) / rate(dashbase_indexer_full_latency_secs_count{table=~'${table:pipe}',app='$app'}[$duration])) by ($per, type)",
     "legendFormat": "{{type}} segments - {{$per}}"
    }
   ]
  },
  {
   "title": "Flush Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(floor(rate(dashbase_indexer_flush_bytes_sum{table=~'${table:pipe}',app='$app'}[$duration])/rate(dashbase_indexer_flush_bytes_count{table=~'${table:pipe}',app='$app'}[$duration]))) by ($per,type)",
     "legendFormat": "{{type}} segments - {{$per}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "min(jvm_attribute_uptime{component='indexer',table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_cpu_usage_percent{component='indexer',table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "{{$per}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_heap_used{component='indexer',table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "{{$per}}"
    },
    {
     "expr": "sum(jvm_memory_heap_max{component='indexer',table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "max - {{$per}}"
    }
   ]
  },
  {
   "title": "GC time spent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(jvm_gc_G1_Young_Generation_time{app='$app',component='indexer',table=~'${table:pipe}'}[$duration])) by ($per)",
     "legendFormat": "young gen - {{$per}}"
    },
    {
     "expr": "sum(irate(jvm_gc_G1_Old_Generation_time{app='$app',component='indexer',table=~'${table:pipe}'}[$duration])) by ($per)",
     "legendFormat": "old gen - {{$per}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(dashbase_disk_used_bytes{table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "reported used bytes - {{$per}}"
    },
    {
     "expr": "sum(dashbase_disk_total_bytes{table=~'${table:pipe}',app='$app'} - dashbase_disk_available_bytes{table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "actual used bytes - {{$per}}"
    },
    {
     "expr": "sum(dashbase_disk_total_bytes{table=~'${table:pipe}',app='$app'}) by ($per)",
     "legendFormat": "total bytes - {{$per}}"
    }
   ]
  }
 ]
}