{
 "title": "Dashbase Auth",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(dashbase_table_info, app)"
   },
   { "name": "duration", "query": "1m,5m,15m" }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "instance count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(up{app='$app',component='auth'}) by (component)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "jvm_cpu_usage_percent{component='auth',app='$app'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "expr": " max(jvm_attribute_uptime{component='auth',app='$app'})"
    }
   ]
  },
  {
   "title": "GC time spent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_G1_Young_Generation_time{app='$app',component='auth'}[$duration])",
     "legendFormat": "young gen - {{instance}}"
    },
    {
     "expr": "rate(jvm_gc_G1_Old_Generation_time{app='$app',component='auth'}[$duration])",
     "legendFormat": "old gen - {{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_heap_used{component='auth',app='$app'}",
     "legendFormat": "used - {{instance}}"
    },
    {
     "expr": "jvm_memory_heap_max{component='auth',app='$app'}",
     "legendFormat": "max - {{instance}}"
    }
   ]
  }
 ]
}