{
 "title": "Dashbase Web",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(jvm_attribute_uptime, app)"
   },
   { "name": "duration", "query": "1m,5m,15m" },
   {
    "name": "table",
    "query": "label_values(jvm_attribute_uptime{app='$app'}, table)"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "instance count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(up{app='$app',component='web'}) by (component)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "jvm_cpu_usage_percent{component='web',app='$app'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "expr": " max(jvm_attribute_uptime{component='web',app='$app'})"
    }
   ]
  },
  {
   "title": "GC time spent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_G1_Young_Generation_time{app='$app',component='web'}[$duration])",
     "legendFormat": "young gen - {{instance}}"
    },
    {
     "expr": "rate(jvm_gc_G1_Old_Generation_time{app='$app',component='web'}[$duration])",
     "legendFormat": "old gen - {{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_heap_used{component='web',app='$app'}",
     "legendFormat": "used - {{instance}}"
    },
    {
     "expr": "jvm_memory_heap_max{component='web',app='$app'}",
     "legendFormat": "max - {{instance}}"
    }
   ]
  },
  {
   "title": "Thead Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_count{component='web',app='$app'}",
     "legendFormat": "threads - {{instance}}"
    }
   ]
  }
 ]
}