{
 "title": "etcd",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(jvm_attribute_uptime, app)"
   },
   {
    "name": "instance",
    "query": "label_values(process_resident_memory_bytes, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "etcd memory",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "{{$instance}}"
    }
   ]
  },
  {
   "title": "etcd proposals",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_proposals_committed_total{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "committed total {{$instance}}"
    },
    {
     "expr": "etcd_server_proposals_applied_total{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "applied total {{$instance}}"
    },
    {
     "expr": "etcd_server_proposals_failed_total{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "failed total {{$instance}}"
    }
   ]
  },
  {
   "title": "etcd leader election",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_has_leader{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "has leader {{$instance}}"
    },
    {
     "expr": "etcd_server_is_leader{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "leader {{$instance}}"
    },
    {
     "expr": "etcd_server_has_leader{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "has leader {{$instance}}"
    }
   ]
  },
  {
   "title": "etcd health",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_health_failures{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "failures {{$instance}}"
    },
    {
     "expr": "etcd_server_health_success{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "success {{$instance}}"
    },
    {
     "expr": "etcd_server_heartbeat_send_failures_total{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "heartbeat failures {{$instance}}"
    }
   ]
  },
  {
   "title": "etcd errors",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_read_indexes_failed_total{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "read failed {{$instance}}"
    },
    {
     "expr": "etcd_server_slow_apply_total{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "slow apply {{$instance}}"
    },
    {
     "expr": "etcd_server_slow_read_indexes_total{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "slow reader indexes total {{$instance}}"
    },
    {
     "expr": "etcd_debugging_server_lease_expired_total{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "lease expired total {{$instance}}"
    }
   ]
  },
  {
   "title": "backend quota",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "etcd_server_quota_backend_bytes{dashbase_io_app='$app', instance=~'${instance:pipe}'}",
     "legendFormat": "quota bytes {{$instance}}"
    }
   ]
  }
 ]
}