{
 "title": "Kubelet",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(kubelet_runtime_operations, instance)"
   },
   {
    "name": "node",
    "query": "label_values(kubelet_runtime_operations, node)"
   },
   { "name": "duration", "query": "1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Runtime Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors_total{instance=~'${instance:pipe}',node=~'${node:pipe}'}[$duration])) by (operation_type)",
     "legendFormat": "total error rate - {{operation_type}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(kubelet_runtime_operations_latency_microseconds{quantile=\"0.99\",instance=~'${instance:pipe}',node=~'${node:pipe}'}) by (operation_type)",
     "legendFormat": "p99 - {{operation_type}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{instance=~'${instance:pipe}',node=~'${node:pipe}'}[$duration])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{instance=~'${instance:pipe}',node=~'${node:pipe}'}[$duration])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "PLEG Relist", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(kubelet_pleg_relist_interval_seconds_bucket{instance=~'${instance:pipe}',node=~'${node:pipe}'}[$duration])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_interval_seconds_bucket{instance=~'${instance:pipe}',node=~'${node:pipe}'}[$duration])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_pleg_relist_latency_microseconds{quantile=\"0.99\",instance=~'${instance:pipe}',node=~'${node:pipe}'}",
     "legendFormat": "p99 - {{instance}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(kubelet_pleg_relist_duration_seconds_bucket{instance=~'${instance:pipe}',node=~'${node:pipe}'}[$duration])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_duration_seconds_bucket{instance=~'${instance:pipe}',node=~'${node:pipe}'}[$duration])) by (le))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}