{
 "title": "Night Watch",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "show tag values with key = host"
   }
  ]
 },
 "panels": [
  {
   "title": "Local Probe - Write Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "query": "SELECT derivative(\"file-append-total-size\", 1s) FROM \"nightwatch-metric\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "file-append-total-size" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "filebeat" }
     ]
    }
   ]
  },
  {
   "title": "Diff Status",
   "type": "graph",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Diff append",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "query": "SELECT \"diff-append\" FROM \"nightwatch-metric\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "diff-append" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "filebeat" }
     ]
    },
    {
     "alias": "diff new",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "query": "SELECT \"diff-new\" FROM \"nightwatch-metric\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "diff-new" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "filebeat" }
     ]
    },
    {
     "alias": "diff nochange",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "query": "SELECT \"diff-nochange\" FROM \"nightwatch-metric\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "diff-nochange" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "filebeat" }
     ]
    },
    {
     "alias": "diff rotate",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "query": "SELECT \"diff-rotate\" FROM \"nightwatch-metric\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "diff-rotate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "filebeat" }
     ]
    }
   ]
  },
  {
   "title": "Each status diff plan",
   "type": "graph",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "run spent time",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "query": "SELECT \"run-spent-time-nanosecond\" FROM \"nightwatch-metric\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "run-spent-time-nanosecond" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "exclude_count",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "select": [
      [
       { "params": [ "exclude_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "filebeat" }
     ]
    },
    {
     "alias": "glob_count",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "query": "SELECT \"glob_count\" FROM \"nightwatch-metric\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "glob_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "filebeat" }
     ]
    }
   ]
  },
  { "title": "DEBUG", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Diff  Error Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Null",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "query": "SELECT \"diff-null\" FROM \"nightwatch-metric\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "diff-null" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "filebeat" }
     ]
    },
    {
     "alias": "diff rotate ignore",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "query": "SELECT \"diff-r-ignore\" FROM \"nightwatch-metric\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "diff-r-ignore" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "filebeat" }
     ]
    },
    {
     "alias": "diff rotate old state not found",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "query": "SELECT \"diff-r-noexists\" FROM \"nightwatch-metric\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "diff-r-noexists" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "filebeat" }
     ]
    }
   ]
  },
  {
   "title": "Diff Plan Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "AS_COUNT",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "query": "SELECT \"as_count\" FROM \"nightwatch-metric\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "as_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "filebeat" }
     ]
    },
    {
     "alias": "AS_UNION_OS_COUNT",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "query": "SELECT \"as_union_os_count\" FROM \"nightwatch-metric\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "as_union_os_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "filebeat" }
     ]
    },
    {
     "alias": "OS_COUNT",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "query": "SELECT \"os_count\" FROM \"nightwatch-metric\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "os_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "filebeat" }
     ]
    }
   ]
  },
  {
   "title": "Deep find count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "deepfind_count",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nightwatch-metric",
     "query": "SELECT \"deepfind_count\" FROM \"nightwatch-metric\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "deepfind_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "filebeat" }
     ]
    }
   ]
  }
 ]
}