{
 "title": "NightWatch Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "label_values(nightwatch_metric_as_count,host)"
   }
  ]
 },
 "panels": [
  { "title": "Verify", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "File count check",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host Local",
     "expr": "nightwatch_verify_local_count{host=~\"${hostname:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{host}} local",
     "measurement": "nightwatch-verify",
     "select": [
      [
       { "params": [ "local_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "$tag_host Local",
     "expr": "nightwatch_verify_dashbase_count{host=~\"${hostname:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{host}} dashbase",
     "measurement": "nightwatch-verify",
     "select": [
      [
       { "params": [ "local_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Count percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nightwatch_verify_count_delta_percentile{host=~\"${hostname:pipe}\"}",
     "legendFormat": "{{ host }} percentile"
    },
    {
     "expr": "nightwatch_verify_count_delta{host=~\"${hostname:pipe}\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  { "title": "Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "File count check",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host Local",
     "expr": "nightwatch_verify_local_count{host=~\"${hostname:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{host}}",
     "measurement": "nightwatch-verify",
     "select": [
      [
       { "params": [ "local_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Time Used", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Verify local used time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_host file counts",
     "expr": "nightwatch_verify_local_used_nanosecond{host=~\"${hostname:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "nightwatch-verify",
     "select": [
      [
       { "params": [ "local_used_nanosecond" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Verify query used time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_host file counts",
     "expr": "nightwatch_verify_dashbase_query_used_nanosecond{host=~\"${hostname:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "nightwatch-verify",
     "select": [
      [
       { "params": [ "dashbase_query_used_nanosecond" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "File count check used time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_host file counts",
     "expr": "nightwatch_count_local_used_nanosecond{host=~\"${hostname:pipe}\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "nightwatch-count",
     "select": [
      [
       { "params": [ "local_used_nanosecond" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "expr": "http_system_load_norm_5{host=~\"${hostname}\"}",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ host }}",
       "measurement": "http",
       "select": [
        [
         { "params": [ "system_load_norm_5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Allocated",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "http_beat_memstats_memory_alloc{host=~\"${hostname}\"}",
       "legendFormat": "{{ host }}"
      }
     ]
    }
   ]
  }
 ]
}