{
 "title": "WebRTC",
 "tags": [ "webrtc" ],
 "time": { "from": "2020-06-24T02:06:06.937Z", "to": "2020-06-24T02:28:57.815Z" },
 "templating": {
  "list": [
   { "name": "call_id", "label": "Call ID" },
   { "name": "participant_id", "label": "Participant ID" },
   { "name": "ssrc", "label": "ssrc" },
   { "name": "query", "query": "*" },
   { "name": "table", "query": "webrtc" },
   { "name": "from" },
   { "name": "to" }
  ]
 },
 "panels": [
  { "title": "RTCIceCandidatePair", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_audio*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "Sent - Audio"
    },
    {
     "expr": "bytesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_audio*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "Received - Audio"
    },
    {
     "expr": "bytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_video*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "Sent - Video"
    },
    {
     "expr": "bytesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_video*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "Received - Video"
    }
   ]
  },
  {
   "title": "Data Rate - Audio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(bytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_audio*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}[5m])",
     "legendFormat": "Bytes Sent"
    },
    {
     "expr": "rate(bytesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_audio*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}[5m])",
     "legendFormat": "Bytes Received"
    },
    {
     "expr": "rate(bytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_audio*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}[5m])*8",
     "legendFormat": "Bits Sent"
    },
    {
     "expr": "rate(bytesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_audio*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}[5m])*8",
     "legendFormat": "Bits Received"
    }
   ]
  },
  {
   "title": "Data Rate - Video",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(bytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_video*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}[5m])",
     "legendFormat": "Bytes Sent"
    },
    {
     "expr": "rate(bytesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_video*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}[5m])",
     "legendFormat": "Bytes Received"
    },
    {
     "expr": "rate(bytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_video*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}[5m])*8",
     "legendFormat": "Bits Sent"
    },
    {
     "expr": "rate(bytesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_video*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}[5m])*8",
     "legendFormat": "Bits Received"
    }
   ]
  },
  {
   "title": "Requests Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "requestsSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_audio*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "audio"
    },
    {
     "expr": "requestsSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_video*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": " video"
    }
   ]
  },
  {
   "title": "Requests Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "requestsReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_audio*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "audio"
    },
    {
     "expr": "requestsReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_video*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "video"
    }
   ]
  },
  {
   "title": "Responses Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "responsesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_audio*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "audio"
    },
    {
     "expr": "responsesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_video*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "video"
    }
   ]
  },
  {
   "title": "Responses Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "responsesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_audio*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "audio"
    },
    {
     "expr": "responsesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_video*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "video"
    }
   ]
  },
  {
   "title": "Consent Requests Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consentRequestsSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_audio*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "audio"
    },
    {
     "expr": "consentRequestsSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",transportId=\"rtctransport_video*\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "video"
    }
   ]
  },
  {
   "title": "Total Round Trip Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "totalRoundTripTime{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "total rtt"
    }
   ]
  },
  {
   "title": "RTT (Round Trip Time)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "totalRoundTripTime{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}/responsesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCIceCandidatePair\"}",
     "legendFormat": "rtt"
    }
   ]
  },
  { "title": "RTCInboundRTPAudioStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Bytes Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bytesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPAudioStream\"}",
     "legendFormat": "bytes received"
    }
   ]
  },
  {
   "title": "Bits Received per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "rate(bytesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPAudioStream\"}[5m])*8",
     "legendFormat": "bytes received / s"
    }
   ]
  },
  {
   "title": "Packets Lost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packetsLost{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPAudioStream\"}",
     "legendFormat": "packets lost"
    }
   ]
  },
  {
   "title": "Packets Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packetsReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPAudioStream\"}",
     "legendFormat": "packets received"
    }
   ]
  },
  {
   "title": "Packets Lost %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(packetsLost{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPAudioStream\"}/packetsReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPAudioStream\"})*100.0",
     "legendFormat": "packets received"
    }
   ]
  },
  {
   "title": "Last Packet Received Timestamp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lastPacketReceivedTimestamp{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPAudioStream\"}",
     "legendFormat": "last packet rcvd timestamp"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitter{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPAudioStream\"}",
     "legendFormat": "jitter"
    }
   ]
  },
  { "title": "RTCInboundRTPVideoStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Bytes Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bytesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}",
     "legendFormat": "bytes received"
    }
   ]
  },
  {
   "title": "Bytes Received per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(bytesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}[5m])",
     "legendFormat": "bytes received /s "
    }
   ]
  },
  {
   "title": "Bits Received per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(bytesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}[5m])*8",
     "legendFormat": "bits received / s"
    }
   ]
  },
  {
   "title": "Fir Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "firCount{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}",
     "legendFormat": "fir count"
    }
   ]
  },
  {
   "title": "Nack Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nackCount{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}",
     "legendFormat": "nack count"
    }
   ]
  },
  {
   "title": "Pli Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pliCount{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}",
     "legendFormat": "pli count"
    }
   ]
  },
  {
   "title": "Packets Lost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packetsLost{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}",
     "legendFormat": "Packets Lost"
    }
   ]
  },
  {
   "title": "Packets Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packetsReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}",
     "legendFormat": "Packets Lost"
    }
   ]
  },
  {
   "title": "Packets Lost %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packetsLost{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}/packetsReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}*100.0",
     "legendFormat": "Packets Lost"
    }
   ]
  },
  {
   "title": "QP Sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qpSum{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}",
     "legendFormat": "qp sum"
    }
   ]
  },
  {
   "title": "QP Sum / Frames Decoded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qpSum{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"} / framesDecoded{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}",
     "legendFormat": "qp sum / frame decoded"
    }
   ]
  },
  {
   "title": "Frames Decoded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "framesDecoded{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}",
     "legendFormat": "frames decoded"
    }
   ]
  },
  {
   "title": "Frames Decoded per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(framesDecoded{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}[5m])",
     "legendFormat": "frames decoded / s"
    }
   ]
  },
  {
   "title": "Key Frames Decoded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "keyFramesDecoded{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}",
     "legendFormat": "key frames decoded"
    }
   ]
  },
  {
   "title": "Key Frames Decoded per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 102 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(keyFramesDecoded{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}[5m])",
     "legendFormat": "key frames decoded / s"
    }
   ]
  },
  {
   "title": "Total Decode Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "totalDecodeTime{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}",
     "legendFormat": "total decode time"
    }
   ]
  },
  {
   "title": "Total Decode Time / Frames Decoded in ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "totalDecodeTime{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}/framesDecoded{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}*1000",
     "legendFormat": "total decode time / frames decoded in ms"
    }
   ]
  },
  {
   "title": "Header Bytes Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "headerBytesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}",
     "legendFormat": "Header Bytes Received"
    }
   ]
  },
  {
   "title": "Header Bytes Received per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 111 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(headerBytesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}[5m])",
     "legendFormat": "header bytes received / s"
    }
   ]
  },
  {
   "title": "Header Bits Received per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 111 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(headerBytesReceived{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCInboundRTPVideoStream\"}[5m])*8",
     "legendFormat": "header bits received / s"
    }
   ]
  },
  { "title": "RTCOutboundRTPAudioStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPAudioStream\"}",
     "legendFormat": "bytes sent"
    }
   ]
  },
  {
   "title": "Data Sent per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(bytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPAudioStream\"}[5m])*8",
     "legendFormat": "bits sent / s"
    },
    {
     "expr": "rate(bytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPAudioStream\"}[5m])",
     "legendFormat": "bytes sent / s"
    }
   ]
  },
  {
   "title": "Packets Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packetsSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPAudioStream\"}",
     "legendFormat": "packets sent"
    }
   ]
  },
  {
   "title": "Packets Sent per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(packetsSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPAudioStream\"}[5m])",
     "legendFormat": "packets sent / s"
    }
   ]
  },
  {
   "title": "Retransmitted Packets Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "retransmittedPacketsSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPAudioStream\"}",
     "legendFormat": "retransmitted packets sent"
    }
   ]
  },
  {
   "title": "Retransimitted Packets Sent per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(retransmittedPacketsSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPAudioStream\"}[5m])",
     "legendFormat": "retransmitted packets sent / s"
    }
   ]
  },
  {
   "title": "Retransimitted Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "retransmittedBytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPAudioStream\"}",
     "legendFormat": "retransmitted bytes sent"
    }
   ]
  },
  {
   "title": "Retransimitted Bytes Sent per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 148 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(retransmittedBytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPAudioStream\"}[5m])",
     "legendFormat": "retransmitted bytes sent / s"
    }
   ]
  },
  { "title": "RTCOutboundRTPVideoStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 } },
  {
   "title": "Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}",
     "legendFormat": "bytes sent"
    }
   ]
  },
  {
   "title": "Bytes Sent per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 158 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(bytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}[5m])",
     "legendFormat": "bytes sent / s"
    }
   ]
  },
  {
   "title": "Bits Sent per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 158 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "rate(bytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}[5m])*8",
     "legendFormat": "bits sent / s"
    }
   ]
  },
  {
   "title": "Fir Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "firCount{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}",
     "legendFormat": "fir count"
    }
   ]
  },
  {
   "title": "Nack Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nackCount{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}",
     "legendFormat": "nack count"
    }
   ]
  },
  {
   "title": "Pli Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pliCount{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}",
     "legendFormat": "pli count"
    }
   ]
  },
  {
   "title": "Quality Limitation Resolution Changes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qualityLimitationResolutionChanges{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}",
     "legendFormat": "quality limitation resolution changes"
    }
   ]
  },
  {
   "title": "QP Sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qpSum{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}",
     "legendFormat": "qp sum"
    }
   ]
  },
  {
   "title": "QP Sum / Frames Encoded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qpSum{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"} / framesEncoded{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}",
     "legendFormat": "qp sum / frame encoded"
    }
   ]
  },
  {
   "title": "Frames Encoded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "framesEncoded{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}",
     "legendFormat": "frames encoded"
    }
   ]
  },
  {
   "title": "Frames Encoded per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(framesEncoded{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}[5m])",
     "legendFormat": "frames encoded / s"
    }
   ]
  },
  {
   "title": "Key Frames Encoded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 185 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "keyFramesEncoded{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}",
     "legendFormat": "key frames encoded"
    }
   ]
  },
  {
   "title": "Total Encode Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 185 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "totalEncodeTime{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}",
     "legendFormat": "total encode time"
    }
   ]
  },
  {
   "title": "Total Encode Time / Frames Encoded in ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 185 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "totalEncodeTime{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}/framesEncoded{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}*1000",
     "legendFormat": "total encode time / frames encoded in ms"
    }
   ]
  },
  {
   "title": "Packets Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 194 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packetsSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}",
     "legendFormat": "packets sent"
    }
   ]
  },
  {
   "title": "Packets Sent per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 194 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(packetsSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}[5m])",
     "legendFormat": "packets sent / s"
    }
   ]
  },
  {
   "title": "Total Packet Send Delay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 194 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "totalPacketSendDelay{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}",
     "legendFormat": "total packets send delay"
    }
   ]
  },
  {
   "title": "Total Packet Send Delay / Packets Sent in ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 194 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "totalPacketSendDelay{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"} / packetsSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"} * 1000",
     "legendFormat": "total packets send delay / packets sent in ms"
    }
   ]
  },
  {
   "title": "Retransmitted Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 203 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "retransmittedBytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}",
     "legendFormat": "retransmitted bytes sent"
    }
   ]
  },
  {
   "title": "Retransmitted Bits Sent per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 203 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(retransmittedBytesSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}[5m])*8",
     "legendFormat": "retransmitted bits sent / s"
    }
   ]
  },
  {
   "title": "Retransmitted Packets Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 203 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "retransmittedPacketsSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}",
     "legendFormat": "retransmitted packets sent"
    }
   ]
  },
  {
   "title": "Retransmitted Packets Sent per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 203 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(retransmittedPacketsSent{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCOutboundRTPVideoStream\"}[5m])",
     "legendFormat": "retransmitted packets sent / s"
    }
   ]
  },
  { "title": "RTCRemoteInboundRTPAudioStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 212 } },
  {
   "title": "Packets Lost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 213 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packetsLost{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCRemoteInboundRTPAudioStream\"}",
     "legendFormat": "packets lost"
    }
   ]
  },
  {
   "title": "Packets Lost per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 213 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(packetsLost{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCRemoteInboundRTPAudioStream\"}[5m])",
     "legendFormat": "packets lost / s"
    }
   ]
  },
  {
   "title": "RTT (Round Trip Time)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 222 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "roundTripTime{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCRemoteInboundRTPAudioStream\"}",
     "legendFormat": "rtt"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 222 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitter{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCRemoteInboundRTPAudioStream\"}",
     "legendFormat": "jitter"
    }
   ]
  },
  { "title": "RTCRemoteInboundRTPVideoStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 231 } },
  {
   "title": "Packets Lost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 232 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packetsLost{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCRemoteInboundRTPVideoStream\"}",
     "legendFormat": "packets lost"
    }
   ]
  },
  {
   "title": "Packets Lost per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 232 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(packetsLost{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCRemoteInboundRTPVideoStream\"}[5m])",
     "legendFormat": "packets lost / s"
    }
   ]
  },
  {
   "title": "RTT (Round Trip Time)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 241 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "roundTripTime{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCRemoteInboundRTPVideoStream\"}",
     "legendFormat": "rtt"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 241 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitter{startMs=\"$from\",endMs=\"$to\",call_id=\"$call_id\",ssrc=\"$ssrc\",participant_id=\"$participant_id\",__query__=\"$query\",__table__=\"$table\",type=\"RTCRemoteInboundRTPVideoStream\"}",
     "legendFormat": "jitter"
    }
   ]
  }
 ]
}