version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:curl
    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: build and push image
          command: |
            # Build and push only on master branch or tag is added

            if [ "${CIRCLE_TAG}" != "" -o "${CIRCLE_BRANCH}" == "master" ]; then
              [ "${CIRCLE_TAG}" != "" ] && export TAG=${CIRCLE_TAG} || export TAG=nightly
              docker build -t dashbase/grafana .
              docker push dashbase/grafana

              docker build -t dashbase/grafana:$TAG .
              docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
              docker push dashbase/grafana:$TAG

              docker build -t dashbase/grafana:$TAG-${CIRCLE_SHA1::6} .
              docker push dashbase/grafana:$TAG-${CIRCLE_SHA1::6}

              .circleci/update.sh
            fi

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
