{
 "title": "Dashbase Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(dashbase_table_info, app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Status",
   "type": "table",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{app='$app',component=~'.+'}) by (component)"
    }
   ]
  },
  {
   "title": "Indexing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(avg(rate(dashbase_ingestion_events_total{component='table',app='$app'}[1m]) * on(instance) group_left(table_partition,table_name) dashbase_table_info) by (table_partition,table_name)) by (table_name)",
     "legendFormat": "# events - {{table_name}}"
    },
    {
     "expr": "sum(avg(rate(dashbase_ingestion_event_bytes_total{component='table',app='$app'}[1m]) * on(instance) group_left(table_partition,table_name) dashbase_table_info) by (table_partition,table_name)) by (table_name)",
     "legendFormat": "# bytes - {{table_name}}"
    }
   ]
  },
  {
   "title": "Query",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dashbase_dashbase_api_query_latency_count{app='$app'}[1m])",
     "legendFormat": "QPS"
    },
    {
     "expr": "avg(dashbase_dashbase_api_query_latency{quantile='0.5',app='$app'})",
     "legendFormat": "latency - p50"
    },
    {
     "expr": "avg(dashbase_dashbase_api_query_latency{quantile='0.99',app='$app'})",
     "legendFormat": "latency - p99"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_cpu_usage_percent{component!='table',app='$app'}) by (component)",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "avg(jvm_cpu_usage_percent{component='table',app='$app'} * on(instance) group_left(table_name) dashbase_table_info) by (table_name)",
     "legendFormat": "table - {{table_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_heap_usage{component!='table',app='$app'}) by (component)",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "avg(jvm_memory_heap_usage{component='table',app='$app'} * on(instance) group_left(table_name) dashbase_table_info) by (table_name)",
     "legendFormat": "table - {{table_name}}"
    }
   ]
  }
 ]
}