{
 "title": "Dashbase Table",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(dashbase_table_info, app)"
   },
   {
    "name": "table",
    "query": "label_values(dashbase_table_info{app='$app'}, table_name)"
   },
   { "name": "duration", "query": "1m,5m,15m" }
  ]
 },
 "panels": [
  { "title": "Indexing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "# events indexed / sec" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_ingestion_events_total[$duration]) * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "events - {{table_name}} - {{table_partition}}"
    },
    {
     "expr": "avg(rate(dashbase_ingestion_event_bytes_total[$duration]) * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": " bytes - {{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Delay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "min(dashbase_indexer_delayInSec * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "ingestion - {{table_name}} - {{table_partition}}"
    },
    {
     "expr": "min(dashbase_search_reader_delayInSec * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "indexing - {{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Full Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(dashbase_indexing_full_latency_secs * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "{{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(dashbase_indexed_full_index_duration{quantile='0.5'} * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "p50 - {{table_name}} - {{table_partition}}"
    },
    {
     "expr": "avg(dashbase_indexed_full_index_duration{quantile='0.99'} * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "p99 - {{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Parse Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(dashbase_ingestion_parse_error_total[$duration]) * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "parse error - {{table_name}} - {{table_partition}}"
    },
    {
     "expr": "avg(rate(dashbase_ingestion_parse_skipped_total[$duration]) * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "skipped - {{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Timeslice Range",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(dashbase_time_slice_range_secs * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "{{table_name}} - {{table_partition}}"
    }
   ]
  },
  { "title": "Kafka Firehose", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Record Lag Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    {
     "format": "short",
     "label": "Number of Records Behind Producer"
    }
   ],
   "targets": [
    {
     "expr": "avg(dashbase_firehose_kafka_consumer_fetch_manager_metrics_records_lag_max * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "{{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Consumption Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(dashbase_firehose_kafka_consumer_fetch_manager_metrics_records_consumed_rate * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "records - {{table_name}} - {{table_partition}}"
    },
    {
     "expr": "avg(dashbase_firehose_kafka_consumer_fetch_manager_metrics_bytes_consumed_rate * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "bytes - {{table_name}} - {{table_partition}}"
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Query Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_search_query_latency_count[$duration]) * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "total - {{table_name}} - {{table_partition}}"
    },
    {
     "expr": "sum(rate(dashbase_search_slow_query_total[$duration]) * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "slow query - {{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(dashbase_search_query_latency{quantile='0.5'} * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "p50 - {{table_name}} - {{table_partition}}"
    },
    {
     "expr": "avg(dashbase_search_query_latency{quantile='0.99'} * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "p99 - {{table_name}} - {{table_partition}}"
    }
   ]
  },
  { "title": "Timeslice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Timeslice Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(dashbase_index_timeslice_count * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "timeslice (total) - {{table_name}} - {{table_partition}}"
    },
    {
     "expr": "avg(dashbase_search_reader_cache_count * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "reader (cached) - {{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Reader Cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(dashbase_search_reader_cache_count * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "timeslice (total) - {{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Timeslice Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(dashbase_indexed_full_flush_bytes * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "timeslice (total) - {{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Wait-in-queue latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(dashbase_search_wait_latency{quantile='0.5'} * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition  )",
     "legendFormat": "p50 - {{table_name}} - {{table_partition}}"
    },
    {
     "expr": "avg(dashbase_search_wait_latency{quantile='0.99'} * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition  )",
     "legendFormat": "p99 - {{table_name}} - {{table_partition}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_cpu_usage_percent{component='table'} * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "{{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_heap_used{component='table'} * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "{{table_name}} - {{table_partition}}"
    },
    {
     "expr": "avg(jvm_memory_heap_max{component='table'} * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "max - {{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(dashbase_total_payload_bytes * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "raw bytes - {{table_name}} - {{table_partition}}"
    },
    {
     "expr": "avg(dashbase_total_index_bytes / dashbase_disk_total_bytes * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'}) by (table_name,table_partition)",
     "legendFormat": "% used - {{table_name}} - {{table_partition}}"
    }
   ]
  },
  { "title": "Bloomfilter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Files Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(dashbase_bloomfilter_files_count * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'})",
     "legendFormat": "{{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Elements Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(dashbase_bloomfilter_elements_count * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'})",
     "legendFormat": "{{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "(dashbase_bloomfilter_ram_used_MB * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'})",
     "legendFormat": "{{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "(dashbase_bloomfilter_disk_used_MB * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'})",
     "legendFormat": "{{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Positive Query Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(dashbase_bloomfilter_positive_query_count * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'})",
     "legendFormat": "{{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Negative Query Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(dashbase_bloomfilter_negative_query_count * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'})",
     "legendFormat": "{{table_name}} - {{table_partition}}"
    }
   ]
  },
  {
   "title": "Unknown Segment Query Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(dashbase_bloomfilter_unknown_segment_query_count * on(instance) group_left(table_name,table_partition) dashbase_table_info{table_name=~'${table:pipe}',app='$app'})",
     "legendFormat": "{{table_name}} - {{table_partition}}"
    }
   ]
  }
 ]
}