{
 "title": "Dashbase Proxy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(dashbase_table_info,app)"
   },
   {
    "name": "kafka_topic",
    "query": "label_values(dashbase_proxy_events_received{app='$app'},topic)"
   }
  ]
 },
 "panels": [
  { "title": "Input / Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_proxy_events_received{topic=~'${kafka_topic:pipe}',app='$app'}[1m])) by (topic)",
     "legendFormat": "events received - {{topic}}"
    },
    {
     "expr": "sum(rate(dashbase_proxy_bytes_received{topic=~'${kafka_topic:pipe}',app='$app'}[1m])) by (topic)",
     "legendFormat": "bytes received - {{topic}}"
    }
   ]
  },
  {
   "title": "Output",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_proxy_events_sent{topic=~'${kafka_topic:pipe}',app='$app'}[1m])) by (topic)",
     "legendFormat": "events sent - {{topic}}"
    },
    {
     "expr": "sum(rate(dashbase_proxy_bytes_sent{topic=~'${kafka_topic:pipe}',app='$app'}[1m])) by (topic)",
     "legendFormat": "bytes sent - {{topic}}"
    }
   ]
  },
  {
   "title": "Input - _bulk endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(io_dashbase_esproxy_api_IndexAPI_bulk_count{app='$app'}[1m]))",
     "legendFormat": "request rate"
    },
    {
     "expr": "sum(rate(io_dashbase_esproxy_api_IndexAPI_bulk_exceptions_total{app='$app'}[1m]))",
     "legendFormat": "exception rate"
    },
    {
     "expr": "avg(io_dashbase_esproxy_api_IndexAPI_bulk{quantile='0.5',app='$app'})",
     "legendFormat": "latency (p50)"
    },
    {
     "expr": "avg(io_dashbase_esproxy_api_IndexAPI_bulk{quantile='0.95',app='$app'})",
     "legendFormat": "latency (p95)"
    },
    {
     "expr": "avg(io_dashbase_esproxy_api_IndexAPI_bulk{quantile='0.99',app='$app'})",
     "legendFormat": "latency (p99)"
    }
   ]
  },
  {
   "title": "Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dashbase_proxy_events_parse_error{app='$app'}[1m])) by (topic)",
     "legendFormat": "parse error - {{topic}}"
    },
    {
     "expr": "rate(dashbase_proxy_events_parse_error_total{app='$app'}[1m])",
     "legendFormat": "parse error - total"
    },
    {
     "expr": "sum(rate(dashbase_kafka_failure{app='$app'}[1m]))",
     "legendFormat": "kafka error - total"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_cpu_usage_percent{component='proxy',app='$app'})",
     "legendFormat": "CPU load"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_heap_used{component='proxy',app='$app'}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_heap_max{component='proxy',app='$app'}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}