{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(dashbase_table_info,app)"
   },
   {
    "name": "topic",
    "query": "label_values(kafka_server_brokertopicmetrics_messagesin_total{app='$app'},topic)"
   }
  ]
 },
 "panels": [
  { "title": "Input / Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Rejected Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesrejected_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Produce/Fetch Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_totalproducerequests_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m]))",
     "legendFormat": "produce - {{topic}}"
    },
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_totalfetchrequests_total{component=\"kafka\",topic=~\"${topic:pipe}\",app='$app'}[5m]))",
     "legendFormat": "fetch - {{topic}}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_requestchannel_requestqueuesize{component=\"kafka\",app='$app'})",
     "legendFormat": "request"
    },
    {
     "expr": "sum(kafka_network_requestchannel_requestqueuesize{component=\"kafka\",app='$app'})",
     "legendFormat": "response "
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "avg(irate(process_cpu_seconds_total{component=\"kafka\",app='$app'}[1m]))",
     "legendFormat": "# cores used"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_bytes_used{area='heap',component=\"kafka\",app='$app'})",
     "legendFormat": "used"
    },
    {
     "expr": "avg(jvm_memory_bytes_max{area='heap',component=\"kafka\",app='$app'})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{component=\"kafka\",app='$app'}[5m]))",
     "legendFormat": "time spent in GC"
    }
   ]
  }
 ]
}